# 1.Write a python program to display all the header tags from wikipedia.org.

In [12]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

In [2]:
def get_header_tags(url):
    response=requests.get(url)
    if response.status_code==200:
        soup=BeautifulSoup(response.content)
        header_bags=soup.find_all('span',class_='mw-headline')
        header_texts=[tag.text.strip() for tag in header_bags]
        return header_texts
    else:
        print('Failed to retrieve data from the provided URL.')
url="https://en.wikipedia.org/wiki/Main_Page"
header_tags=get_header_tags(url)
if header_tags:
    print('Header Tags:')
    for tag in  header_tags:
        print(tag)

Header Tags:
Welcome to Wikipedia
From today's featured article
Did you know ...
In the news
On this day
Today's featured picture
Other areas of Wikipedia
Wikipedia's sister projects
Wikipedia languages

In [3]:
response=requests.get('https://en.wikipedia.org/wiki/Main_Page')
response

# 2.Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release) and make data frame.

In [5]:
response=requests.get('https://www.imdb.com/list/ls091520106/')
response

In [71]:
def imdb(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.content)
    movie_name = []
    movie_rate = []
    movie_year = []
        
    for i in soup.find_all('h3', class_="lister-item-header"):
        movie_name_text=i.text.strip()
        movie_name.append(re.split(r'\W+',movie_name_text))
        
    for s in soup.find_all('div', class_="ipl-rating-widget"):
        rating_text = s.text.strip()
        rating = re.search(r'\d+(\.\d+)?', rating_text) 
        if rating:
            movie_rate.append(float(rating.group())) 
        
                    
    for t in soup.find_all('h3', class_="lister-item-header"):
        movie_year_text=t.text.strip()
        movie_year.append(re.search(r'\((\d{4})\)',movie_year_text)[0])
                   
    df = pd.DataFrame({'Movie Name':movie_name,'Movie Rate':movie_rate,'Movie Year':movie_year})
    return df

url ='https://www.imdb.com/list/ls091520106/'
imdb(url)

                                           Movie Name  Movie Rate Movie Year
0             [1, The, Shawshank, Redemption, 1994, ]         9.3     (1994)
1                         [2, The, Godfather, 1972, ]         9.2     (1972)
2               [3, The, Godfather, Part, II, 1974, ]         9.0     (1974)
3                      [4, The, Dark, Knight, 2008, ]         9.0     (2008)
4                         [5, 12, Angry, Men, 1957, ]         9.0     (1957)
..                                                ...         ...        ...
95                 [96, North, by, Northwest, 1959, ]         8.3     (1959)
96                 [97, A, Clockwork, Orange, 1971, ]         8.3     (1971)
97                               [98, Snatch, 2000, ]         8.2     (2000)
98  [99, Le, fabuleux, destin, d, Amélie, Poulain,...         8.3     (2001)
99                            [100, The, Kid, 1921, ]         8.2     (1921)

[100 rows x 3 columns]

# 3. Write a python program to scrape mentioned details from dineout.co.in : i) Restaurant name ii) Cuisine iii) Location iv) Ratings v) Image URL.

In [129]:
import re
def dineout(url):
    response = requests.get(url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.content)
        restaurant_name = []
        cuisine = []
        location = []
        rating = []
        image_url = []
        
        for i in soup.find_all('div', class_='restnt-info cursor'):
            restaurant_name_text=i.text.strip()
            restaurant_name.append(re.split(r'\s*[,]\s*',restaurant_name_text)[0])
        for s in soup.find_all('span', class_='double-line-ellipsis'):
            cuisine_text=s.text.strip()
            cuisine.append(re.split(r'\s*\|\s*', cuisine_text)[-1])
        for t in soup.find_all('div', class_='restnt-loc ellipsis'):
            location.append(t.text.strip())
        for u in soup.find_all('div', class_='restnt-rating rating-4'):
            rating.append(float(u.text.strip()))
        for t in soup.find_all('div', class_='restnt-rating rating-5'):
            rating.append(float(t.text.strip()))  
        for v in soup.find_all('img', class_='no-img'):
            image_url.append(v['data-src'])
        
       
        
        df = pd.DataFrame({
            'Restaurant-Name': restaurant_name,
            'Cuisine': cuisine,
            'Location': location,
            'Rating': rating,
            'Image-Url': image_url
        })
        return df
    else:
        print('Failed to retrieve data')

url = "https://www.dineout.co.in/delhi-restaurants"
dineout(url)

,Restaurant-Name,Cuisine,Location,Rating,Image-Url
0,Delia My Bar HeadquartersKarol Bagh,"North Indian, Chinese, Fast Food, Beverages","Karol Bagh, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...
1,The G.T. RoadM-Block,North Indian,"M-Block,Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
2,Berco'sConnaught Place,"Chinese, Thai","Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
3,My Bar HeadquartersConnaught Place,"North Indian, Chinese","Connaught Place, Central Delhi",4.0,https://im1.dineout.co.in/images/uploads/resta...
4,Article 21Connaught Place,"North Indian, Chinese, South Indian","Connaught Place, Central Delhi",3.8,https://im1.dineout.co.in/images/uploads/resta...
5,Unplugged CourtyardConnaught Place,"North Indian, Italian, Chinese, Turkish, Conti...","Connaught Place, Central Delhi",4.0,https://im1.dineout.co.in/images/uploads/resta...
6,Punjab GrillJanpath,"North Indian, Mughlai","Janpath, Central Delhi",3.7,https://im1.dineout.co.in/images/uploads/resta...
7,SliceConnaught Place,"Italian, Fast Food","Connaught Place, Central Delhi",4.4,https://im1.dineout.co.in/images/uploads/resta...
8,Kwality RestaurantRegal Cinema Complex,"North Indian, Continental, Mughlai","Regal Cinema Complex,Connaught Place, Central ...",4.4,https://im1.dineout.co.in/images/uploads/resta...
9,Nando'sM-Block,"Portuguese, Mediterranean, Desserts, Beverages","M-Block,Connaught Place, Central Delhi",4.0,https://im1.dineout.co.in/images/uploads/resta...
10,Hard Rock CafeConnaught Place,"American, Continental, Finger Food","Connaught Place, Central Delhi",4.0,https://im1.dineout.co.in/images/uploads/resta...
11,SubwayConnaught Place,Fast Food,"Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
12,Cafe MRPConnaught Place,"North Indian, Continental, Italian, Finger Foo...","Connaught Place, Central Delhi",4.4,https://im1.dineout.co.in/images/uploads/resta...
13,Fa YianConnaught Place,Chinese,"Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
14,LocalScindia House,"North Indian, Asian, Continental","Scindia House,Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
15,Oddly PubConnaught Place,"North Indian, Chinese, Italian, Continental","Connaught Place, Central Delhi",5.0,https://im1.dineout.co.in/images/uploads/resta...
16,SandozConnaught Place,"North Indian, Continental","Connaught Place, Central Delhi",4.9,https://im1.dineout.co.in/images/uploads/resta...
17,Kill The BillConnaught Place,"Fast Food, North Indian, Seafood, Chinese, Con...","Connaught Place, Central Delhi",5.0,https://im1.dineout.co.in/images/uploads/resta...
18,Minar RestaurantConnaught Place,"North Indian, Chinese","Connaught Place, Central Delhi",5.0,https://im1.dineout.co.in/images/uploads/resta...
19,The Junkyard CafeConnaught Place,"North Indian, Continental, Chinese, Fast Food","Connaught Place, Central Delhi",4.8,https://im1.dineout.co.in/images/uploads/resta...
20,The EmbassyConnaught Place,"North Indian, European, Fast Food, Italian, Co...","Connaught Place, Central Delhi",5.0,https://im1.dineout.co.in/images/uploads/resta...

# 4.Write s python program to display list of respected former finance minister of India(i.e. Name , Term of office) from https://presidentofindia.nic.in/former-presidents.htm and make data frame.

In [70]:
def former_president(url):
    response=requests.get(url)
    if response.status_code==200:
        soup=BeautifulSoup(response.content)
        presidents=[]
        for i in soup.find_all('div',class_='president-listing'):
            presidents.append(i.text.strip())
        termofoffice=[]
        for s in soup.find_all('h5'):
            termofoffice.append(s.text.strip())
        df=pd.DataFrame({'Presidents':presidents,'Term of Office':termofoffice})
        return df
    else:
        print('Failed to retrieve the data')
url='https://presidentofindia.nic.in/former-presidents'
former_president(url)

                                           Presidents           Term of Office
0       Shri Ram Nath Kovind\n14th President of India  14th President of India
1      Shri Pranab Mukherjee\n13th President of India  13th President of India
2   Smt Pratibha Devisingh Patil\n12th President o...  12th President of India
3     DR. A.P.J. Abdul Kalam\n11th President of India  11th President of India
4       Shri K. R. Narayanan\n10th President of India  10th President of India
5    Dr Shankar Dayal Sharma\n9th  President of India  9th  President of India
6         Shri R Venkataraman\n8th President of India   8th President of India
7            Giani Zail Singh\n7th President of India   7th President of India
8   Shri Neelam Sanjiva Reddy\n6th President of India   6th President of India
9    Dr. Fakhruddin Ali Ahmed\n5th President of India   5th President of India
10  Shri Varahagiri Venkata Giri\n4th President of...   4th President of India
11           Dr. Zakir Husain\n3rd President of India   3rd President of India
12  Dr. Sarvepalli Radhakrishnan\n2nd President of...   2nd President of India
13        Dr. Rajendra Prasad\n1st President of India   1st President of India